name: Main
on: [push]

jobs:
  build_test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          cache: maven

      - uses: actions/checkout@v4
        with:
          ref: main
          repository: vasudevan-s/UnifiedTestFramework

      - name: Install unified test framework dependency with Maven
        run: |
            mvn clean install --file pom.xml
            cache: maven
  

      - uses: actions/checkout@v4
        with:
            ref: main
            repository: vasudevan-s/TestDataFramework-Java

      - name: Install test data framework dependency with Maven
        run: |
          mvn clean install --file pom.xml
          cache: maven

      - uses: actions/checkout@v4
      - name: Build project with Maven
        run: |
          mvn clean test -Dsuites=src/test/resources/Web.xml -Dthreads=1 package --file pom.xml
 #         mvn -B package --file pom.xml