name: Apple e-Commerce Shop Web Automation Suite Test
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build_test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
#          cache: maven

      - name: Install Google Chrome 
        uses: browser-actions/setup-chrome@v1
        with:
#            chrome-version: 120
            install-chromedriver: true

      - name: Checkout source for UnifiedTestFramework
        uses: actions/checkout@v4
        with:
          ref: main
          repository: vasudevan-s/UnifiedTestFramework

      - name: Install unified test framework dependency
        run: |
            mvn clean install --file pom.xml
  
      - name: Checkout source for Test Data Framework
        uses: actions/checkout@v4
        with:
            ref: main
            repository: vasudevan-s/TestDataFramework-Java

      - name: Install test data framework dependency
        run: |
          mvn clean install --file pom.xml

      - name: Checkout source for ${{ github.event.repository.name }}
        uses: actions/checkout@v4

      - name: Build project with Maven
        run: |
          mvn clean test -Dsuites=src/test/resources/Web.xml -Dthreads=1 package --file pom.xml
 #         mvn -B package --file pom.xml