name: Apple E-Commerce Shop Automation Tests

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]
    workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./src/

        strategy:
            matrix:
                java-version: [23]

                steps:
                    - name: Checkout code
                    - uses: actions/checkout@v4

                    - name: Set up JDK 23
                      uses: actions/setup-java@v4
                      with:
                        java-version: '23'
                        distribution: 'temurin'
                        cache: maven

                    - name: Build with Maven
                      run: mvn clean test -Dsuites=src/test/resources/Web.xml -Dthreads=3 package --file pom.xml
